theme: jekyll-theme-cayman
title: "Work From Home Forever"
description: "A list of companies letting their employees work from home for an indefinite period even after COVID-19 restrictions are over"
